// <auto-generated />
using System;
using Manisai_PL_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Manisai_PL_App.Migrations
{
    [DbContext(typeof(PlappContext))]
    [Migration("20261004040112_ChangeAccnumberToLong")]
    partial class ChangeAccnumberToLong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Manisai_PL_App.Models.Aadharmaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aadharnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Fathername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middlename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aadharmasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Bankdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accholdername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Accnumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Acctype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Appid")
                        .HasColumnType("int");

                    b.Property<string>("Bankbranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bankname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ifsccode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Appid");

                    b.ToTable("Bankdetails");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Basicdetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aadharnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Appstage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Appstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Emailid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leadid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pannumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pincode")
                        .HasColumnType("int");

                    b.Property<string>("Statusremarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BasicDetail", (string)null);
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Companydetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companyaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companymailid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companyname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Grossincome")
                        .HasColumnType("int");

                    b.Property<int?>("Obligations")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("Companydetails");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Companymaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companyname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companymasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Doctypemaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Doctype")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctypemasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Docuploaddetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Appid")
                        .HasColumnType("int");

                    b.Property<string>("Docpath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doctype")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Appid");

                    b.ToTable("Docuploaddetails");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Loandetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Appid")
                        .HasColumnType("int");

                    b.Property<int?>("Appliedamount")
                        .HasColumnType("int");

                    b.Property<int?>("Appliedtenure")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Approvaldate")
                        .HasColumnType("date");

                    b.Property<int?>("Approvedamount")
                        .HasColumnType("int");

                    b.Property<decimal?>("Approvedemi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Approvedroi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Approvedtenure")
                        .HasColumnType("int");

                    b.Property<decimal?>("Emi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Roi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Appid");

                    b.ToTable("Loandetails");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Otpmaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OtpCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Otpmasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Panmaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Fathername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middlename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pancardnumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Panmasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Personaldetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Appid")
                        .HasColumnType("int");

                    b.Property<string>("Currentaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fathername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mothername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permanentaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference1email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference1mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference1name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference1relation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference2email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference2mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference2name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference2relation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Appid");

                    b.ToTable("Personaldetails");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Pincodemaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Circle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pincode")
                        .HasColumnType("int");

                    b.Property<byte?>("Servicable")
                        .HasColumnType("tinyint");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Village")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pincodemasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Rulesmaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Maxvalue")
                        .HasColumnType("int");

                    b.Property<int?>("Minvalue")
                        .HasColumnType("int");

                    b.Property<string>("Rulename")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rulesmasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Usermaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usermasters");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Bankdetail", b =>
                {
                    b.HasOne("Manisai_PL_App.Models.Basicdetail", "App")
                        .WithMany("Bankdetails")
                        .HasForeignKey("Appid");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Companydetail", b =>
                {
                    b.HasOne("Manisai_PL_App.Models.Basicdetail", "App")
                        .WithMany("Companydetails")
                        .HasForeignKey("AppId");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Docuploaddetail", b =>
                {
                    b.HasOne("Manisai_PL_App.Models.Basicdetail", "App")
                        .WithMany("Docuploaddetails")
                        .HasForeignKey("Appid");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Loandetail", b =>
                {
                    b.HasOne("Manisai_PL_App.Models.Basicdetail", "App")
                        .WithMany("Loandetails")
                        .HasForeignKey("Appid");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Personaldetail", b =>
                {
                    b.HasOne("Manisai_PL_App.Models.Basicdetail", "App")
                        .WithMany("Personaldetails")
                        .HasForeignKey("Appid");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Manisai_PL_App.Models.Basicdetail", b =>
                {
                    b.Navigation("Bankdetails");

                    b.Navigation("Companydetails");

                    b.Navigation("Docuploaddetails");

                    b.Navigation("Loandetails");

                    b.Navigation("Personaldetails");
                });
#pragma warning restore 612, 618
        }
    }
}
